apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
data:
  db-port: "3307"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 20
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  labels:
    app: api-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /mnt/efs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi  # Define the desired storage capacity
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      initContainers:
      - name: setup-permissions
        image: busybox
        command: ["sh", "-c", "chmod 777 -R /mnt/efs"]
        volumeMounts:
        - name: api-storage
          mountPath: /mnt/efs
      containers:
      - name: sample-api
        image: dockerrexxzz/dj:latest # Replace with your Docker image name and tag
        imagePullPolicy: Always
        resources:
          limits:
            memory: "250Mi" # Adjust the memory limit as per your requirements
            cpu: "0.25"     # Adjust the CPU limit as per your requirements
          requests:
            memory: "125Mi"
            cpu: "0.1"
        ports:
        - name: api
          containerPort: 7000
        readinessProbe:
          httpGet:
            path: /home  # Adjust the path based on your application's health check endpoint
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /home  # Adjust the path based on your application's health check endpoint
            port: 7000
          initialDelaySeconds: 15
        volumeMounts:
        - name: api-config
          mountPath: /app/secrets.json
          subPath: secrets.json
        - name: api-storage
          mountPath: /mnt/efs
      volumes:
      - name: api-config
        configMap:
          name: myconfigmap
      - name: api-storage
        persistentVolumeClaim:
          claimName: api-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: my-lb
spec:
  selector:
    app: sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 7000
  type: LoadBalancer