apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api
  template:
    metadata:
      labels:
        app: sample-api
    spec:
      initContainers:
      - name: setup-permissions
        image: busybox
        command: ["sh", "-c", "chmod 777 -R /mnt/efs"]  # Set permissions for the volume
        volumeMounts:
          - name: api-storage
            mountPath: /mnt/efs
      containers:
      - name: sample-api
        image: dockerrexxzz/dj:v1  # Replace with your Docker image name and tag
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: secret-env
        resources:
          limits:
            memory: "256Mi"  # Adjust the memory limit as per your requirements
            cpu: "256m"       # Adjust the CPU limit as per your requirements
          requests:
            memory: "125Mi"
            cpu: "100m"
        ports:
          - name: sample-port
            containerPort: 7000
        readinessProbe:
          httpGet:
            path: /home  # Adjust the path based on your application's health check endpoint
            port: 7000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /home  # Adjust the path based on your application's health check endpoint
            port: 7000
          initialDelaySeconds: 15
        volumeMounts:
          - name: api-storage
            mountPath: /mnt/efs
          - name: secret-json
            mountPath: /app/config/secrets.json
            subPath: secrets.json
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pvc
        - name: secret-json
          configMap:
            name: secrets-json
