# PersistentVolume definition for EFS storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-pv
  labels:
    app: api-pv
spec:
  accessModes:
    - ReadWriteOnce  # Defines how the volume can be accessed
  capacity:
    storage: 1Gi  # Storage capacity of the PV
  hostPath:
    path: /mnt/efs  # Path on the host where the PV is mounted
  persistentVolumeReclaimPolicy: Retain  # Retain the PV after it's released
  storageClassName: manual  # Custom storage class
