# PersistentVolumeClaim to request storage from the PersistentVolume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sample-pvc
  namespace: default
spec:
  resources:
    requests:
      storage: 1Gi  # Define the desired storage capacity
  accessModes:
    - ReadWriteMany  # Define how the PVC can be accessed
  storageClassName: manual  # Match the PV's storage class