# Service to expose the sample-api application within the cluster
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: irwinrex
spec:
  selector:
    app: sample-pod  # Match pods with this label
    pod : sample-api # Label selector for the pod
  ports:
    - name: sample-svc-port
      protocol: TCP
      port: 8000  # Service <your-namespace>port
      targetPort: sample-pod-port  # Port on the pod
  type: ClusterIP  # Service type
