# Service to expose the sample-api application within the cluster
apiVersion: v1
kind: Service
metadata:
  name: sample-service
spec:
  selector:
    app: sample-api  # Match pods with this label
  ports:
    - name: sample-service-port
      protocol: TCP
      port: 8000  # Service port
      targetPort: sample-pod-port  # Port on the pod
  type: ClusterIP  # Service type